### ISSUE TITLE
Python 3 version?

### ISSUE THREAD

**Issue by Shotgunosine** [trislett/TFCE_mediation#4]
Are there any plans to port this to Python 3?

**Comment by trislett** [comment]
Support for python 3 is eventually planned but not until the tm_multimodal scripts are no longer alpha (but before Numpy stops supporting python 2.7).
Do you have a specific reason why you would want to use python 3 over 2.7?

**Comment by Shotgunosine** [comment]
I've got a package running TFCE that also depends on rpy2, which has
stopped supporting python 2.7. I've moved pretty much all of my code over
to python 3.

**Comment by trislett** [comment]
Thank you for letting me know (I thought rpy2 was planning to support python 2.7). 
Likely the TFCE and adjacency functions will still work in python 3. They are ported from c++ and c using Cython. However, I can't guarantee anything until I fully test TFCE_mediation with python 3.

**Comment by trislett** [comment]
Just a follow-up to the python 3 question. I'm planning to have full support by the end of January.

**Comment by trislett** [comment]
@Shotgunosine , there is now beta support for python 3.5 -- checkout the python3support branch. I'll merge the branches and upload it to pypipe when I've tested it more.

**Comment by trislett** [comment]
Closing. TFCE_mediation support python 3.5
